# Домашнее задание NumPy

#### Импортируйте NumPy

#### Создайте массив из 5 нулей 

array([0., 0., 0., 0., 0.])

#### Создайте массив из 5 единиц

array([1., 1., 1., 1., 1.])

#### Создайте массив из 5 десяток

array([10., 10., 10., 10., 10.])

#### Создайте массив из целых чисел от 20 до 42

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42])

#### Создайте массив нечетных чисел от 20 до 42

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41])

#### Создайте матрицу 3x3 целых чисел от 20 до 28

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

#### Создайте единичную матрицу 5x5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Сгенерите рандомное число от 0 до 1

In [12]:
np.random.seed(42)


array([0.37454012])

#### Сгенерируйте массив из 20 рандомных чисел из нормального распределения

In [14]:
np.random.seed(42)


array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
       -0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783,
       -0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ])

#### Создайте подобную матрицу:

array([[0.01, 0.03, 0.05, 0.07, 0.09],
       [0.11, 0.13, 0.15, 0.17, 0.19],
       [0.21, 0.23, 0.25, 0.27, 0.29],
       [0.31, 0.33, 0.35, 0.37, 0.39],
       [0.41, 0.43, 0.45, 0.47, 0.49],
       [0.51, 0.53, 0.55, 0.57, 0.59],
       [0.61, 0.63, 0.65, 0.67, 0.69],
       [0.71, 0.73, 0.75, 0.77, 0.79],
       [0.81, 0.83, 0.85, 0.87, 0.89],
       [0.91, 0.93, 0.95, 0.97, 0.99]])

#### Создайте массив из 30 равномерно распределенных между 0 и 1 чисел:

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

## Numpy индексация и выбор

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [21]:
# Пишите свой код здесь.
# Иначе, если вы используете ячейку ниже, то не увидите больше тот результат, который надо повторить.

array([[16, 17, 18, 19, 20, 21],
       [23, 24, 25, 26, 27, 28],
       [30, 31, 32, 33, 34, 35],
       [37, 38, 39, 40, 41, 42],
       [44, 45, 46, 47, 48, 49]])

In [25]:
# Пишите свой код здесь.
# Иначе, если вы используете ячейку ниже, то не увидите больше тот результат, который надо повторить.

26

In [27]:
# Пишите свой код здесь.
# Иначе, если вы используете ячейку ниже, то не увидите больше тот результат, который надо повторить.

array([[ 2],
       [ 9],
       [16]])

In [29]:
# Пишите свой код здесь.
# Иначе, если вы используете ячейку ниже, то не увидите больше тот результат, который надо повторить.

array([29, 30, 31, 32, 33, 34, 35])

In [31]:
# Пишите свой код здесь.
# Иначе, если вы используете ячейку ниже, то не увидите больше тот результат, который надо повторить.

array([[22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

#### Посчитайте сумму всех значений в матрице mat

1225

#### Каково стандартное отклонение в mat?

14.142135623730951

#### Посчитайте сумму значений в каждом столбце матрицы mat

array([154, 161, 168, 175, 182, 189, 196])

# Отличная работа!